# Face Recognition on image

In [1]:
import numpy as np
import cv2

# Loading the required haar-cascade xml classifier file
face = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
#eye = cv2.CascadeClassifier('haarcascade_eye.xml')

# Reading the image
img = cv2.imread('hello2.jpg')
# Converting image to grayscale because initiall image in three layers i.e. rgb so convert into one layer
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Applying the face detection method on the grayscale image
faces = face.detectMultiScale(gray, 1.1, 5)
print(faces)

# Iterating through rectangles of detected faces
for (x,y,w,h) in faces:
    img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),thickness=2)
#     roi_gray = gray[y:y+h, x:x+w]
#     roi_color = img[y:y+h, x:x+w]
    
#     eyes = eye.detectMultiScale(roi_gray)
#     for (ex,ey,ew,eh) in eyes:
#         cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)

cv2.imshow('img',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[276  40  76  76]
 [386  83  80  80]
 [138 145  84  84]
 [221 117  83  83]
 [497   3  78  78]
 [750 106  95  95]
 [604  45  90  90]
 [ 57  11  82  82]]


# Face Recognition on Video

In [1]:
import cv2
cascade=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye = cv2.CascadeClassifier('haarcascade_eye.xml')
cap=cv2.VideoCapture(0)
while True:
    ret,img=cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    plate_rect=cascade.detectMultiScale(gray,1.1,10)

    for (x,y,w,h) in plate_rect: 
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0,),2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = img[y:y+h, x:x+w]
        eyes = eye.detectMultiScale(roi_gray,1.1, 3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
        
    cv2.imshow('detect', img)
    if cv2.waitKey(1) == 27:
        break
        
cap.release()
cv2.destroyAllWindows()

In [3]:
# Face Recognition and eye

# Importing the libraries
import cv2

# Loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

# Defining a function that will do the detections
def detect(gray, frame):
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x+w, y+h), (255, 0, 0), 2)
        roi_gray = gray[y:y+h, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.1, 3)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex+ew, ey+eh), (0, 255, 0), 2)
    return frame

# Doing some Face Recognition with the webcam
video_capture = cv2.VideoCapture(0)
while True:
    _, frame = video_capture.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = detect(gray, frame)
    cv2.imshow('Video', canvas)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
video_capture.release()
cv2.destroyAllWindows()

In [5]:
import cv2
import numpy as np

width=1980
height=1080

cam=cv2.VideoCapture(0,cv2.CAP_DSHOW)
cam.set(cv2.CAP_PROP_FRAME_WIDTH,width)
cam.set(cv2.CAP_PROP_FRAME_HEIGHT,height)
cam.set(cv2.CAP_PROP_FPS,30)
cam.set(cv2.CAP_PROP_FOURCC,cv2.VideoWriter_fourcc(*'MJPG'))


faceCascade=cv2.CascadeClassifier(r'haarcascade_frontalface_default.xml')
faceCascade2=cv2.CascadeClassifier(r'haarcascade_eye.xml')
while True:
    _,frame=cam.read()
    frGray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)

    faces=faceCascade.detectMultiScale(frGray,1.3,5)
    faces1=faceCascade2.detectMultiScale(frGray,1.3,5)
    print(faces)
    for face in faces:
        x,y,w,h=face
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,0),3)
    for face in faces1:
        x1,y1,w1,h1=face
        cv2.rectangle(frame,(x1,y1),(x1+w1,y1+h1),(0,0,255),3)
    cv2.imshow('MY cam',frame)
  
    
   
   
    cv2.moveWindow('MY cam',0,0)
    

    
    if cv2.waitKey(1) & 0xff == ord('q'):
        break
cam.release()

()
()
()
()
()
[[734 333  79  79]]
()
()
()
[[599 268 283 283]]
[[598 269 284 284]]
[[594 265 290 290]]
[[610 276 255 255]]
[[610 281 255 255]]
[[601 276 255 255]]
[[584 267 280 280]]
()
[[596 278 255 255]]
()
()
()
()
()
()
[[725 323  87  87]]
()
[[730 323  82  82]]
[[733 325  79  79]]
[[732 323  82  82]]
()
()
()
()
[[735 324  79  79]]
()
()
()
()
()
()
[[729 325  76  76]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[742 330  64  64]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[747 334  61  61]]
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
()
[[580 282 268 268]]
[[569 277 286 286]]
[[582 285 272 272]]
()
[[586 282 277 277]]
[[592 287 263 263]]
[[587 284 274 274]]
[[585 282 277 277]]
[[587 275 280 280]]
()
[[585 278 277 277]]
[[585 277 280 280]]
[[594 280 268 268]]
()
()
()
()
()
()
[[591 276 268 268]]
[[593 275 266 266]]
[[583 272 283 283]]
[[582